CREATE TABLE [dbo].[ApprovedQualificationsImport]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[DateOfOfqualDataSnapshot] DATETIME NULL,
	[QualificationName] NVARCHAR(255) NULL,
	[AwardingOrganisation] NVARCHAR(255) NULL,
	[QualificationNumber] NVARCHAR(20) NULL,
	[Level] NVARCHAR(255) NULL,
	[QualificationType] NVARCHAR(255) NULL,
	[Subcategory] NVARCHAR(255) NULL,
	[SectorSubjectArea] NVARCHAR(255) NULL,
	[Status] NVARCHAR(255) NULL,
	[Age1416FundingAvailable] BIT NOT NULL,
	[Age1416FundingApprovalStartDate] DATETIME NULL,
	[Age1416FundingApprovalEndDate] DATETIME NULL,
	[Age1416Notes] NVARCHAR(255) NULL,
	[Age1619FundingAvailable] BIT NOT NULL,
	[Age1619FundingApprovalStartDate] DATETIME NULL,
	[Age1619FundingApprovalEndDate] DATETIME NULL,
	[Age1619Notes] NVARCHAR(255) NULL,
	[LocalFlexibilitiesFundingAvailable] BIT NOT NULL,
	[LocalFlexibilitiesFundingApprovalStartDate] DATETIME NULL,
	[LocalFlexibilitiesFundingApprovalEndDate] DATETIME NULL,
	[LocalFlexibilitiesNotes] NVARCHAR(255) NULL,
	[LegalEntitlementL2L3FundingAvailable] BIT NOT NULL,
	[LegalEntitlementL2L3FundingApprovalStartDate] DATETIME NULL,
	[LegalEntitlementL2L3FundingApprovalEndDate] DATETIME NULL,
	[LegalEntitlementL2L3Notes] NVARCHAR(255) NULL,
	[LegalEntitlementEnglishandMathsFundingAvailable] BIT NOT NULL,
	[LegalEntitlementEnglishandMathsFundingApprovalStartDate] DATETIME NULL,
	[LegalEntitlementEnglishandMathsFundingApprovalEndDate] DATETIME NULL,
	[LegalEntitlementEnglishandMathsNotes] NVARCHAR(255) NULL,
	[DigitalEntitlementFundingAvailable] BIT NOT NULL,
	[DigitalEntitlementFundingApprovalStartDate] DATETIME NULL,
	[DigitalEntitlementFundingApprovalEndDate] DATETIME NULL,
	[DigitalEntitlementNotes] NVARCHAR(255) NULL,
	[ESFLevel34FundingAvailable] BIT NOT NULL,
	[ESFLevel34FundingApprovalStartDate] DATETIME NULL,
	[ESFLevel34FundingApprovalEndDate] DATETIME NULL,
	[ESFLevel34Notes] NVARCHAR(255) NULL,
	[AdvancedLearnerLoansFundingAvailable] BIT NOT NULL,
	[AdvancedLearnerLoansFundingApprovalStartDate] DATETIME NULL,
	[AdvancedLearnerLoansFundingApprovalEndDate] DATETIME NULL,
	[AdvancedLearnerLoansNotes] NVARCHAR(255) NULL,
	[AwardingOrganisationURL] NVARCHAR(255) NULL,
	[L3FreeCoursesForJobsFundingAvailable] BIT NOT NULL,
	[L3FreeCoursesForJobsFundingApprovalStartDate] DATETIME NULL,
	[L3FreeCoursesForJobsFundingApprovalEndDate] DATETIME NULL,
	[L3FreeCoursesForJobsNotes] NVARCHAR(255) NULL,
	[QualificationNumberVarchar] VARCHAR(100) NULL,
		
	CONSTRAINT [PK_ApprovedQualification] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

